@Controller_based_API_HostAddress = http://localhost:5263

### Post a new Todo item
POST {{Controller_based_API_HostAddress}}/api/todo
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}
###
@id=1
GET {{Controller_based_API_HostAddress}}/api/todo/{{id}}
###
    {
    "id": 1,
    "name": "walk dog",
    "isComplete": true
    }
###
PUT {{Controller_based_API_HostAddress}}/api/todo/1
Content-Type: application/json

{
    "id": 1,
    "name": "feed fish",
    "isComplete": false
}
###
DELETE {{Controller_based_API_HostAddress}}/api/todo/1
{
}
###
